# Set title for project documentation
site_name: vmilabs

# Set the name of author. This will add a meta data tag to the generated HTML header
site_author: Kai.Zhou
copyright: 'Copyright &copy; 2019 - 2023 Kai.Zhou'
theme:
  language: 'zh'
  name: 'material'
  features:
    - navigation.tabs
  icon:
    logo: 'material/cloud'
markdown_extensions:
  - admonition
  - codehilite
nav:
  - 'Home': 
    - 'Home': index.md
    
